### ISSUE TITLE
boot macos from XXXX 之后一半重启

### ISSUE THREAD

**Issue by zheng0301211** [josways/XiaoMi-Ruby-15.6-2019#11]
macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后  ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？

【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。

**Comment by zb2947244682** [comment]
...

**Comment by zb2947244682** [comment]
> macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> 
> 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。

电脑型号没错吧？？？

**Comment by zheng0301211** [comment]
我又重新安装 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版]，安装界面完成后 重启 重新进入 报错。 更换为你的EFI ，白苹果进度条跑一半就重启。
### **电脑型号如下：**
https://item.mi.com/product/10000141.html?selected=10000141&pClass=p
小米笔记本15.6" 2019款 独显版
i5-8250U + 8G +MX110

**Comment by Jxh98** [comment]
> 我又重新安装 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版]，安装界面完成后 重启 重新进入 报错。 更换为你的EFI ，白苹果进度条跑一半就重启。
> 
> ### **电脑型号如下：**
> https://item.mi.com/product/10000141.html?selected=10000141&pClass=p
> 小米笔记本15.6" 2019款 独显版
> i5-8250U + 8G +MX110

https://www.sqlsec.com/2018/08/clover.html

**Comment by zheng0301211** [comment]
安装我知道怎么安装，  我安装了好几个版本，但是都不完美，我换了之前10.14.5的集成的EFI 能进入系统了。主要是想偷下懒用下你的EFI直接驱动。就避免我自己去找驱动了。

**Comment by zb2947244682** [comment]
> 安装我知道怎么安装， 我安装了好几个版本，但是都不完美，我换了之前10.14.5的集成的EFI 能进入系统了。主要是想偷下懒用下你的EFI直接驱动。就避免我自己去找驱动了。

跟你情况一样啊，，咋整，。

**Comment by Jxh98** [comment]
好吧 等我国庆休假的时候排查一下吧
你们可以先用 另外一位大佬的
XenOriginal/XiaoMi-Ruby-15.6-UMA-only

**Comment by zb2947244682** [comment]
> macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> 
> 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。

这个EFI是可以驱动DW1820A网卡的，但是我们都没装，所以我感觉是这个原因。

> macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> 
> 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。

这个EFI是可以驱动DW1820A网卡的，但是我们都没装，所以我感觉是这个原因。

**Comment by zb2947244682** [comment]
> 安装我知道怎么安装， 我安装了好几个版本，但是都不完美，我换了之前10.14.5的集成的EFI 能进入系统了。主要是想偷下懒用下你的EFI直接驱动。就避免我自己去找驱动了。

这个EFI是可以驱动DW1820A网卡的，但是我们都没装，所以我感觉是这个原因。

**Comment by zb2947244682** [comment]
> macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> 
> 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。

我已经验证了，是因为没装DW1820A网卡导致的。装了立马就好了

**Comment by xdd3234** [comment]
你好，我是同款配置，想知道怎么去除dw1820的驱动，怕启动不了，我打算一直用外置

**Comment by Mike-hd123** [comment]
> > macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> > 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。
> 
> 我已经验证了，是因为没装DW1820A网卡导致的。装了立马就好了

**Comment by Mike-hd123** [comment]
> > macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> > 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。
> 
> 我已经验证了，是因为没装DW1820A网卡导致的。装了立马就好了

没有安装的可以删除驱动吗，怎么删除。

**Comment by Mike-hd123** [comment]
> > macOS Mojave 10.14.5(18F132) Installer with Clover 4928 安装后可直接进入系统，但自带键盘、声音、触摸板无法使用， 使用你的EFI替换后 ，选择boot macos from XXXX 之后白苹果进程一半重启。是只能10.14.6吗？
> > 【黑果小兵】macOS Mojave 10.14.6 18G87 正式版 with Clover 5050原版镜像[双EFI双平台终极版] 该版本 也无法进入系统。 可否提供你的安装系统版本链接。
> 
> 我已经验证了，是因为没装DW1820A网卡导致的。装了立马就好了

删除后显示com.apple.applefscompressiontypezlib load succeeded！

**Comment by josways** [comment]
建议拔掉自带的网卡，或者购买dw1820的网卡
