### ISSUE TITLE
关于alc256一点问题

### ISSUE THREAD

**Issue by a37324614** [josways/XiaoMi-Ruby-15.6-2019#18]
我从linux下提取的speaker的线路 为0x1b 利用黑果小兵的方法想仿冒 但是发现没有 Pin Default 这个玩意 所以想和您讨论一下这块声卡的仿冒

**Comment by MaximKiselev** [comment]
hi, do u have installed system on notebook
can u check  https://techposts.org/fix-realtek-alc256-audio-macos-hackintosh/... trick for patch codeccommander.

**Comment by a37324614** [comment]
I'm trying

**Comment by josways** [comment]
yeah , i will be try it .

**Comment by a37324614** [comment]
Seemingly not

**Comment by MaximKiselev** [comment]
i find additional model with alc256m. Xiaomi Notebook Pro 15.6 with 10Gen of CPU
Intel Core i5-10210U/Intel Core i7-10510U/NVIDIA GeForce MX250
basically, there is a chance to fix it in the future....

**Comment by XenOriginal** [comment]
采用了intel smart tchnology， windows下不装驱动也没法驱动，所以外放能驱动的概率比较低

**Comment by a37324614** [comment]
估计是烂掉了 打算卖了买一台能正常支持的笔记本

**Comment by josways** [comment]
干不动
