### ISSUE TITLE
ruby I7 替换EFI安装失败

### ISSUE THREAD

**Issue by q127981** [josways/XiaoMi-Ruby-15.6-2019#19]
大佬你好，我用你这个EFI替换后，无法进入安装页面。但是我用了小米pro的efi替换后，可以进入安装页面。现在有以下问题：
1.蓝牙
2.声卡外放
3.触摸板
4.独显

请问一下，是哪个配置不兼容吗？导致我无法使用你这个efi，请教下蓝牙和触摸板问题怎么解决。

**Comment by q127981** [comment]
我的电脑是 小米 ruby 15.3  I7的

**Comment by Missyouag** [comment]
如果你是2018版的，需要使用https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only/tree/48b11d8c87bd170d2a3eddfa5e11029ea8bd2733 ；更新到最新是换框架，可能不兼容旧系统，需要重装(我没弄好,有数据不想重装)，另外，可能他们说的配件你没有购买，比如WiFi芯片。触摸板需要装一个软件，按别人的流程走是ok的。

**Comment by josways** [comment]
蓝牙，无线网络，请选择白果卡。
声卡外放 暂时解决不了，
触控板，需要重建缓存 ``` sudo kextcache -i /  ```
独显除非nVidia出面解决，
