### ISSUE TITLE
Try to make Alc256 work together

### ISSUE THREAD

**Issue by XenOriginal** [josways/XiaoMi-Ruby-15.6-2019#8]
lol

**Comment by Jxh98** [comment]
it's so hard!

**Comment by MaximKiselev** [comment]
hi, do u have weird problem with external sound.. i mean any news about alc256m. does all work good

**Comment by Jxh98** [comment]
> hi, do u have weird problem with external sound.. i mean any news about alc256m. does all work good

It doesn't work. Maybe modifying the bios will fix it.

**Comment by XenOriginal** [comment]
已放弃，中间隔了一层Intel dsp，应该需要特定驱动不好仿冒
