### ISSUE TITLE
卡在引导安装页面，同款I5的配置

### ISSUE THREAD

**Issue by cqtangrenjie** [josways/XiaoMi-Ruby-15.6-2019#9]
用了你的EFI后会卡在 进入安装页面前的白苹果那里，读完条后 就重启，请问知道怎么回事吗？

**Comment by cqtangrenjie** [comment]
现在在clover页面选择安装mac，就会跳转到bios 设置里面。。请问有解决方案吗?镜像用的10.14.4 18E226的

**Comment by Jxh98** [comment]
## 介绍
所安装的系统版本为 10.14.6

**Comment by Jxh98** [comment]
https://www.sqlsec.com/2018/08/clover.html

**Comment by Jxh98** [comment]
好吧 等我国庆休假的时候排查一下吧
你们可以先用 另外一位大佬的
[XenOriginal/XiaoMi-Ruby-15.6-UMA-only](https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only)

**Comment by zb2947244682** [comment]
> 好吧 等我国庆休假的时候排查一下吧
> 你们可以先用 另外一位大佬的
> [XenOriginal/XiaoMi-Ruby-15.6-UMA-only](https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only)

你自己装了DW1820A，但是我们的电脑是没有的，我怀疑是这个问题。大佬～

**Comment by CladoniaTeam** [comment]
同样是这个问题

**Comment by josways** [comment]
关于 安装的时候 卡白苹果 卡啰嗦模式 
拔掉自带的网卡就好了
